version: '3.8'

services:
  app:
    build: .
    container_name: leadsync-api
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/leadsync
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest 
    container_name: leadsync-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
